name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print working directory
      run: pwd
    - name: Show files
      run: ls
    
    - name: Build the Docker image
      run: docker build backend/ --tag my-image-name:$(date +%s)
